coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 5%
    patch: no
  notify:
    slack:
      default:
        url: "secret:m4WVFfUBxrTFhs78vbHCJMH0eMDtlOOGlIWx9HlcjvK7pfdoKzrnq12OG+fXE3Wsr+5I6U4i8VO6Rr66wuI8MtimddjEUNiNWyswiRD1bpyoQIh9oDhgfZQbANqwtqH9cSIjl8/ffcJYgTIBiEBsKBhqb6aRJBVEJI8QhdG8iGo="
        threshold: 0%
        only_pulls: false
        branches: null
        flags: null
        paths: null
