[build]
  # This is the directory to change to before starting a build.
  base    = "bartop-ui"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "bartop-ui/build"
  # This will be your default build command
  command = "npm run build"
