openapi: 3.0.0
info:
  title: BarTop API
  description: API for interacting with BarTop data
  version: 0.0.1
  contact:
    name: 'BarTop Dev Team'
    url: https://github.com/dpopp07/bartop/issues
  license:
    name: 'MIT'

servers:
  - url: http://localhost:3001
    description: Local development server

# define security as global, protecting all endpoints
security:
  - Auth0: []

paths:
  /drinks:
    get:
      operationId: listDrinks
      summary: Get a list of all drinks.
      description: Returns an object containing an array of all drinks.
      responses:
        '200':
          description: Returned list of all the drinks.
          content:
            application/json:
              schema:
                type: object
                required:
                  - items
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Drink'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/GeneralError'

  /users:
    post:
      summary:
      description:
      operationId: createUser
      requestBody:
        required: true
        description: JSON object containing the new User to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: New User successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '406':
          $ref: '#/components/responses/InvalidContentType'
        '422':
          $ref: '#/components/responses/InvalidBodyModel'
        '500':
          $ref: '#/components/responses/GeneralError'
    get:
      operationId: listUsers
      summary: Get a list of all users.
      description: Returns an object containing an array of all users.
      responses:
        '200':
          description: Returned list of all the users.
          content:
            application/json:
              schema:
                type: object
                required:
                  - items
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/GeneralError'

components:

  securitySchemes:
    Auth0:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    # error responses
    GeneralError:
      description: Internal server error.

    Unauthorized:
      description: Access token is missing or invalid.

    NonExistant:
      description: Route does not exist.

    InvalidContentType:
      description: Invalid content type.

    InvalidBodyModel:
      description: Invalid model in body.


    # model definitions
    User:
      type: object
      required:
        - auth0Id
      properties:
        authoId:
          type: string
          description: The user ID generated by Auth0, used to distinguish users at login. It is required for posting new users to the database.
        id:
          $ref: '#/components/schemas/ID'

    Drink:
      type: object
      required:
        - name
        - ingredients
      properties:
        name:
          type: string
          description: Name of the cocktail.
        ingredients:
          type: array
          description: The ingredients that make up the cocktail.
          items:
            type: object
            required:
              - ingredient
            properties:
              ingredient:
                type: string
                description: The specific ingredient to be used. e.g. whiskey, simple syrup, etc.
              amount:
                type: object
                required:
                  - quantity
                  - unit
                properties:
                  quantity:
                    type: double
                    description: The numeric amount of the ingredient to be used.
                  unit:
                    type: string
                    description: The unit given to the numeric quantity of the ingredient.
        instructions:
          type: array
          description: List of instructions describing how to make the cocktail.
          items:
            type: string
        description:
          type: string
          description: Breif summary describing the cocktail's flavor profile, history, etc.
        id:
          $ref: '#/components/schemas/ID'

    Catalog:
      type: object
      required:
        - userId
      properties:
        userId:
          type: string
          description: Unique identifier for the user that the catalog belongs to.
        drinkIds:
          type: array
          description: List of identifiers for the drinks in the catalog.
          items:
            type: string
        id:
          $ref: '#/components/schemas/ID'

    ID:
      type: string
      description: The database generated ID. This is not applicable for requests but will always be present in responses.
